<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE exams [<!ELEMENT exams (exam+)>

<!ELEMENT exam (name, state, city) >

<!ELEMENT name (#PCDATA) >

<!ELEMENT state (#PCDATA) >

<!ELEMENT city (#PCDATA) >

<!ATTLIST exam id CDATA #REQUIRED >]>

<exams>

  <exam id="1">

    <name>Roywon</name>

    <state>california</state>

    <city>sanfrancisco</city>

  </exam>

  <exam id="2">

    <name>arlan</name>

    <state>california</state>

    <city>sanjose</city>

  </exam>

</exams>




